kind: Deployment
apiVersion: apps/v1
metadata:
  name: test
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: jodios/game:v5
          imagePullPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
