kind: Deployment
apiVersion: apps/v1
metadata:
  name: test
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: jodios/game:v5
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
---
kind: Service
apiVersion: v1
metadata:
  name: test
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: UDP
  selector:
    app: test
---
kind: Service
apiVersion: v1
metadata:
  name: test-nodeport
  namespace: prod
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30000
      name: tcp-protocol
    - port: 8080
      targetPort: 8080
      protocol: UDP
      nodePort: 30000
      name: udp-protocol
  selector:
    app: test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: test
  namespace: prod
spec:
  rules:
  - host: testing.jodios.com
    http:
      paths:
      - backend:
          service:
            name: test
            port:
              number: 80
        pathType: ImplementationSpecific
---
apiVersion: k8s.nginx.org/v1alpha1
kind: GlobalConfiguration
metadata:
  name: nginx-configuration
  namespace: prod
spec:
  listeners:
  - name: dns-udp
    port: 8080
    protocol: UDP
  - name: dns-tcp
    port: 8080
    protocol: TCP