kind: Deployment
apiVersion: apps/v1
metadata:
  name: test
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: jodios/game:v5
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: UDP
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
---
kind: Service
apiVersion: v1
metadata:
  name: test
  namespace: prod
spec:
  type: NodePort
  ports:
    # - port: 8080
    #   targetPort: 8080
    #   protocol: TCP
    - port: 8080
      targetPort: 8080
      protocol: UDP
      nodePort: 30000
  selector:
    app: test
---
kind: Service
apiVersion: v1
metadata:
  name: fogload-test
  namespace: prod
spec:
  type: NodePort
  ports:
    # - port: 8080
    #   targetPort: 8080
    #   protocol: TCP
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30001
  selector:
    app: fogload
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: test
#   namespace: prod
# spec:
#   type: ClusterIP
#   ports:
#     # - port: 8080
#     #   targetPort: 8080
#     #   protocol: TCP
#     - port: 8080
#       targetPort: 8080
#       protocol: UDP
#   selector:
#     app: test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: test
  namespace: prod
spec:
  rules:
  - host: testing.jodios.com
    http:
      paths:
      - backend:
          service:
            name: test
            port:
              number: 8080
        pathType: ImplementationSpecific